version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    depends_on:
      - db

  web:
    image: nginx:latest
    container_name: laravel_web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf:/etc/nginx/conf.d
    depends_on:
      - app

  db:
    image: mysql:8.4
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata: